export const LETTER_STORIES: Record<string, string> = {
  A: "An amazing alligator ate an apple. He asked the ant for another apple! Awesome!",
  B: "A big brown bear bounced a blue ball. The ball broke a bowl!",
  C: "The cute cat caught a cold. She wore a coat to get cozy.",
  D: "The dog dug a deep hole in the dirt. He found a dinosaur bone!",
  E: "An elephant ate an egg every evening. He had enormous ears!",
  F: "Four funny frogs flipped in the fountain. They found a fish!",
  G: "A green gorilla grabbed some grapes. He gave them to a goose.",
  H: "A happy hippo hid in the house. He wore a heavy hat.",
  I: "An iguana eats insects in the igloo. It is freezing ice!",
  J: "The jellyfish jumped in the jam. It was a joyful journey!",
  K: "The kind kangaroo kicked a kite. The koala kept it.",
  L: "A little lion licked a lemon. He laughed loudly!",
  M: "The monkey made a massive mess. He mixed mud and milk!",
  N: "Nine newts nap in the nest. A nice nightingale sings.",
  O: "An octopus opened an orange. The owl watched outside.",
  P: "A pink pig played in the puddle. He painted a picture.",
  Q: "The queen quietly quilted a blanket. The quail quacked quickly.",
  R: "A red rabbit ran a race. He rode a rocket to the roof!",
  S: "A snake slithered on the sand. The sun shone in the sky.",
  T: "The tall tiger touched his toes. He took a train to town.",
  U: "The unicorn used an umbrella. Up, up it flew in the universe!",
  V: "A vampire bat visited a volcano. He drove a velvet van.",
  W: "The walrus walked in the water. He wore a warm wool sweater.",
  X: "An ox took an x-ray of a fox. They played a xylophone.",
  Y: "A yellow yak yawned yesterday. He ate yummy yogurt.",
  Z: "The zebra zipped his zipper. He zoomed through the zoo!"
};
