import type { LetterData } from '../types';

export const LETTERS_DATA: LetterData[] = [
  { letter: 'A', uppercase: 'A', lowercase: 'a', phoneme: '/æ/', exampleWord: 'Apple', exampleEmoji: '🍎', funFact: 'A is the most used vowel in English!', color: '#EF4444', bgColor: '#FEF2F2', objects: ['🍎 Apple', '✈️ Aeroplane', '🐊 Alligator'] },
  { letter: 'B', uppercase: 'B', lowercase: 'b', phoneme: '/b/', exampleWord: 'Ball', exampleEmoji: '⚽', funFact: 'B looks like two bubbles on a stick — can you see them?', color: '#F97316', bgColor: '#FFF7ED', objects: ['⚽ Ball', '🦋 Butterfly', '🐻 Bear'] },
  { letter: 'C', uppercase: 'C', lowercase: 'c', phoneme: '/k/', exampleWord: 'Cat', exampleEmoji: '🐱', funFact: 'There are around 600 million pet cats in the world!', color: '#F59E0B', bgColor: '#FFFBEB', objects: ['🐱 Cat', '🍰 Cake', '🚗 Car'] },
  { letter: 'D', uppercase: 'D', lowercase: 'd', phoneme: '/d/', exampleWord: 'Dog', exampleEmoji: '🐶', funFact: 'Dinosaurs started with D — there were over 700 kinds!', color: '#84CC16', bgColor: '#F7FEE7', objects: ['🐶 Dog', '🦕 Dinosaur', '🥁 Drum'] },
  { letter: 'E', uppercase: 'E', lowercase: 'e', phoneme: '/ɛ/', exampleWord: 'Elephant', exampleEmoji: '🐘', funFact: 'E is the most common letter in English!', color: '#22C55E', bgColor: '#F0FDF4', objects: ['🐘 Elephant', '🥚 Egg', '✏️ Eraser'] },
  { letter: 'F', uppercase: 'F', lowercase: 'f', phoneme: '/f/', exampleWord: 'Fish', exampleEmoji: '🐟', funFact: 'Fish have been on Earth for over 500 million years!', color: '#14B8A6', bgColor: '#F0FDFA', objects: ['🐟 Fish', '🌸 Flower', '🦊 Fox'] },
  { letter: 'G', uppercase: 'G', lowercase: 'g', phoneme: '/g/', exampleWord: 'Giraffe', exampleEmoji: '🦒', funFact: 'A giraffe\'s tongue is 45cm long and dark purple!', color: '#06B6D4', bgColor: '#ECFEFF', objects: ['🦒 Giraffe', '🍇 Grapes', '🎸 Guitar'] },
  { letter: 'H', uppercase: 'H', lowercase: 'h', phoneme: '/h/', exampleWord: 'Horse', exampleEmoji: '🐴', funFact: 'Horses can sleep both standing up and lying down!', color: '#3B82F6', bgColor: '#EFF6FF', objects: ['🐴 Horse', '🏠 House', '🌻 Hat'] },
  { letter: 'I', uppercase: 'I', lowercase: 'i', phoneme: '/ɪ/', exampleWord: 'Ice Cream', exampleEmoji: '🍦', funFact: 'Ice cream was invented over 2,000 years ago in China!', color: '#6366F1', bgColor: '#EEF2FF', objects: ['🍦 Ice cream', '🏝️ Island', '🦎 Iguana'] },
  { letter: 'J', uppercase: 'J', lowercase: 'j', phoneme: '/dʒ/', exampleWord: 'Jellyfish', exampleEmoji: '🪼', funFact: 'Jellyfish have no brain, heart, or bones!', color: '#8B5CF6', bgColor: '#F5F3FF', objects: ['🪼 Jellyfish', '🤹 Juggler', '🦘 Jaguar'] },
  { letter: 'K', uppercase: 'K', lowercase: 'k', phoneme: '/k/', exampleWord: 'Kangaroo', exampleEmoji: '🦘', funFact: 'Baby kangaroos are called joeys and are born tiny as a jellybean!', color: '#EC4899', bgColor: '#FDF2F8', objects: ['🦘 Kangaroo', '🔑 Key', '🪁 Kite'] },
  { letter: 'L', uppercase: 'L', lowercase: 'l', phoneme: '/l/', exampleWord: 'Lion', exampleEmoji: '🦁', funFact: 'A lion\'s roar can be heard 8 kilometres away!', color: '#F43F5E', bgColor: '#FFF1F2', objects: ['🦁 Lion', '🍋 Lemon', '🦎 Lizard'] },
  { letter: 'M', uppercase: 'M', lowercase: 'm', phoneme: '/m/', exampleWord: 'Monkey', exampleEmoji: '🐒', funFact: 'Monkeys can recognise themselves in a mirror!', color: '#EF4444', bgColor: '#FEF2F2', objects: ['🐒 Monkey', '🌙 Moon', '🦋 Moth'] },
  { letter: 'N', uppercase: 'N', lowercase: 'n', phoneme: '/n/', exampleWord: 'Nest', exampleEmoji: '🪺', funFact: 'Some birds weave nests so strong they last for decades!', color: '#F97316', bgColor: '#FFF7ED', objects: ['🪺 Nest', '🌙 Night', '🐢 Newt'] },
  { letter: 'O', uppercase: 'O', lowercase: 'o', phoneme: '/ɒ/', exampleWord: 'Octopus', exampleEmoji: '🐙', funFact: 'An octopus has three hearts and blue blood!', color: '#F59E0B', bgColor: '#FFFBEB', objects: ['🐙 Octopus', '🍊 Orange', '🦉 Owl'] },
  { letter: 'P', uppercase: 'P', lowercase: 'p', phoneme: '/p/', exampleWord: 'Penguin', exampleEmoji: '🐧', funFact: 'Penguins can jump up to 1.8 metres out of the water!', color: '#84CC16', bgColor: '#F7FEE7', objects: ['🐧 Penguin', '🎁 Present', '🦜 Parrot'] },
  { letter: 'Q', uppercase: 'Q', lowercase: 'q', phoneme: '/kw/', exampleWord: 'Queen', exampleEmoji: '👑', funFact: 'Q is the rarest letter — it almost always needs its friend U!', color: '#22C55E', bgColor: '#F0FDF4', objects: ['👑 Queen', '🦆 Quail', '❓ Question'] },
  { letter: 'R', uppercase: 'R', lowercase: 'r', phoneme: '/r/', exampleWord: 'Rainbow', exampleEmoji: '🌈', funFact: 'A rainbow is actually a full circle — we only see half!', color: '#14B8A6', bgColor: '#F0FDFA', objects: ['🌈 Rainbow', '🤖 Robot', '🐇 Rabbit'] },
  { letter: 'S', uppercase: 'S', lowercase: 's', phoneme: '/s/', exampleWord: 'Sun', exampleEmoji: '☀️', funFact: 'The Sun is so big that 1 million Earths could fit inside it!', color: '#06B6D4', bgColor: '#ECFEFF', objects: ['☀️ Sun', '⭐ Star', '🐍 Snake'] },
  { letter: 'T', uppercase: 'T', lowercase: 't', phoneme: '/t/', exampleWord: 'Tiger', exampleEmoji: '🐯', funFact: 'Every tiger has a unique pattern of stripes — just like fingerprints!', color: '#3B82F6', bgColor: '#EFF6FF', objects: ['🐯 Tiger', '🌮 Taco', '🦖 T-Rex'] },
  { letter: 'U', uppercase: 'U', lowercase: 'u', phoneme: '/ʌ/', exampleWord: 'Umbrella', exampleEmoji: '☂️', funFact: 'The umbrella was used for sun protection before rain protection!', color: '#6366F1', bgColor: '#EEF2FF', objects: ['☂️ Umbrella', '🦄 Unicorn', '🐻‍❄️ Urchin'] },
  { letter: 'V', uppercase: 'V', lowercase: 'v', phoneme: '/v/', exampleWord: 'Volcano', exampleEmoji: '🌋', funFact: 'There are over 1,500 active volcanoes on Earth!', color: '#8B5CF6', bgColor: '#F5F3FF', objects: ['🌋 Volcano', '🎻 Violin', '🦁 Viper'] },
  { letter: 'W', uppercase: 'W', lowercase: 'w', phoneme: '/w/', exampleWord: 'Whale', exampleEmoji: '🐋', funFact: 'A blue whale\'s heart is the size of a small car!', color: '#EC4899', bgColor: '#FDF2F8', objects: ['🐋 Whale', '🐺 Wolf', '🍉 Watermelon'] },
  { letter: 'X', uppercase: 'X', lowercase: 'x', phoneme: '/ks/', exampleWord: 'Xylophone', exampleEmoji: '🎵', funFact: 'X is used in mathematics to represent unknown numbers!', color: '#F43F5E', bgColor: '#FFF1F2', objects: ['🎵 Xylophone', '🦊 X-ray fish', '❎ X mark'] },
  { letter: 'Y', uppercase: 'Y', lowercase: 'y', phoneme: '/j/', exampleWord: 'Yak', exampleEmoji: '🐃', funFact: 'Yaks can live at heights of 6,000 metres — higher than most planes!', color: '#EF4444', bgColor: '#FEF2F2', objects: ['🐃 Yak', '🟡 Yellow', '⛵ Yacht'] },
  { letter: 'Z', uppercase: 'Z', lowercase: 'z', phoneme: '/z/', exampleWord: 'Zebra', exampleEmoji: '🦓', funFact: 'Z is the last letter and makes the buzzing sound — just like a bee!', color: '#F97316', bgColor: '#FFF7ED', objects: ['🦓 Zebra', '⚡ Zap', '🤐 Zip'] },
];

export const LETTER_COLORS = LETTERS_DATA.map(l => l.color);
