import type { NumberData } from '../types';

const getImg = (word: string) => `https://img.icons8.com/fluency/200/${word.toLowerCase().replace(/ /g, '-')}.png`;

export const NUMBERS_DATA: NumberData[] = [
  { digit: 0, word: 'Zero', funFact: 'Zero means nothing!', image: getImg('Empty-Box'), color: '#6366F1', bgColor: '#EEF2FF', objects: [] },
  { digit: 1, word: 'One', funFact: 'One sun in the sky!', image: getImg('Sun'), color: '#EF4444', bgColor: '#FEF2F2', objects: [{ name: 'Sun', image: getImg('Sun') }] },
  { digit: 2, word: 'Two', funFact: 'Two eyes to see!', image: getImg('Eye'), color: '#F97316', bgColor: '#FFF7ED', objects: [{ name: 'Eye', image: getImg('Eye') }, { name: 'Ear', image: getImg('Ear') }] },
  { digit: 3, word: 'Three', funFact: 'Three sides on a triangle!', image: getImg('Triangle'), color: '#F59E0B', bgColor: '#FFFBEB', objects: [{ name: 'Triangle', image: getImg('Triangle') }, { name: 'Square', image: getImg('Square') }, { name: 'Circle', image: getImg('Circle') }] },
  { digit: 4, word: 'Four', funFact: 'Four legs on a dog!', image: getImg('Dog'), color: '#84CC16', bgColor: '#F7FEE7', objects: [{ name: 'Apple', image: getImg('Apple') }, { name: 'Orange', image: getImg('Orange') }, { name: 'Lemon', image: getImg('Lemon') }, { name: 'Grapes', image: getImg('Grapes') }] },
  { digit: 5, word: 'Five', funFact: 'Five fingers on your hand!', image: getImg('Hand'), color: '#22C55E', bgColor: '#F0FDF4', objects: [{ name: 'Star', image: getImg('Star') }, { name: 'Flower', image: getImg('Flower') }, { name: 'Mushroom', image: getImg('Mushroom') }, { name: 'Butterfly', image: getImg('Butterfly') }, { name: 'Turtle', image: getImg('Turtle') }] },
  { digit: 6, word: 'Six', funFact: 'Six legs on a bug!', image: getImg('Bug'), color: '#14B8A6', bgColor: '#F0FDFA', objects: [{ name: 'Strawberry', image: getImg('Strawberry') }, { name: 'Cherry', image: getImg('Cherry') }, { name: 'Blueberry', image: getImg('Blueberries') }, { name: 'Peach', image: getImg('Peach') }, { name: 'Pineapple', image: getImg('Pineapple') }, { name: 'Kiwi', image: getImg('Kiwi') }] },
  { digit: 7, word: 'Seven', funFact: 'Seven colors in a rainbow!', image: getImg('Rainbow'), color: '#3B82F6', bgColor: '#EFF6FF', objects: [{ name: 'Rainbow', image: getImg('Rainbow') }, { name: 'Star', image: getImg('Star') }, { name: 'Moon', image: getImg('Moon') }, { name: 'Sun', image: getImg('Sun') }, { name: 'Cloud', image: getImg('Cloud') }, { name: 'Meteor', image: getImg('Meteor') }, { name: 'Galaxy', image: getImg('Galaxy') }] },
  { digit: 8, word: 'Eight', funFact: 'Eight legs on a spider!', image: getImg('Spider'), color: '#8B5CF6', bgColor: '#F5F3FF', objects: [{ name: 'Spider', image: getImg('Spider') }, { name: 'Octopus', image: getImg('Octopus') }, { name: 'Star', image: getImg('Star') }, { name: 'Diamond', image: getImg('Diamond') }, { name: 'Ruby', image: getImg('Ruby') }, { name: 'Emerald', image: getImg('Emerald') }, { name: 'Flower', image: getImg('Flower') }, { name: 'Leaf', image: getImg('Leaf') }] },
  { digit: 9, word: 'Nine', funFact: 'Nine planets (maybe)!', image: getImg('Planet'), color: '#EC4899', bgColor: '#FDF2F8', objects: [{ name: 'Cat', image: getImg('Cat') }, { name: 'Dog', image: getImg('Dog') }, { name: 'Frog', image: getImg('Frog') }, { name: 'Rabbit', image: getImg('Rabbit') }, { name: 'Bear', image: getImg('Bear') }, { name: 'Fox', image: getImg('Fox') }, { name: 'Panda', image: getImg('Panda') }, { name: 'Koala', image: getImg('Koala') }, { name: 'Tiger', image: getImg('Tiger') }] },
];
